name: Rust

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Init Submodules
      run : | 
              git submodule sync
              git submodule init
              git submodule update
              python3.7-config --ldflags --cflags
    - name: Build
      run: cargo build -vv
    - name: Run tests
      run: cargo test -vv
